Repository hackathon20230505/weliving_Front, pull requests merged in 2023-06, with the labels that each got.

#41 [#35] Design 💄 Add Kakao LogIn Button
  src/pages/Intro.tsx
Labels: 🎨 html&css

#44 [#40] Feat: Add login validation
  src/components/LogIn/LogInBody.tsx
Labels: ✨ Feature

#46 [#45] !HOTFIX: Remove parser babel option in prettier
  .prettierrc
Labels: 🐞BugFix

#49 [#42] !HOTFIX: Remove react import
  src/pages/SignUp.tsx
Labels: 🐞BugFix

#53 [#52] Feat: Change login valid default value
  src/components/LogIn/LogInBody.tsx
Labels: ✨ Feature

#54 [#50] Feat: Implement LogIn when click login button
  src/apis/users/signin/signIn.ts
  src/components/LogIn/LogInBody.tsx
Labels: ✨ Feature

#60 [#59] Feat: Add Type Effect Module
  package-lock.json
  package.json
  src/components/MainContent/BackgroundFirst.tsx
  src/components/OnBording/Background.tsx
  src/pages/MainContentFirst.tsx
  src/pages/OnBording.tsx
Labels: 🎨 html&css

#65 [#57] Feat: Implement Home page
  src/components/Home/HomeBody.tsx
  src/pages/ViewMyLetter.tsx
  src/pages/ViewOtherLetter.tsx
  src/pages/WriteLetter.tsx
Labels: ✨ Feature

#68 [#58] Design: Implement Write Letter page
  src/AppRouter.tsx
  src/components/WriteLetter/WriteLetterBody.tsx
  src/components/WriteLetter/WriteLetterHeader.tsx
  src/components/WriteLetter/atoms/isValidPostAtom.tsx
  src/index.css
  src/pages/CollectPersonalInfo.tsx
  src/pages/PrivacyPolicy.tsx
  src/pages/TermsOfService.tsx
  src/pages/WriteLetter.tsx
Labels: 🎨 html&css

#69 !HOTFIX: chage img path
  src/components/Home/HomeBody.tsx
Labels: 🐞BugFix

#79 !HOTFIX: Fixed typescript error
  src/components/AfterWrite/YourHelp.tsx
  src/components/Common/ResizableBottomSheet.tsx
  src/components/LogIn/LogInBody.tsx
  src/components/SignUp/SignUpBody.tsx
  src/components/WriteLetter/WriteLetterBody.tsx
  src/components/WriteLetter/WriteLetterHeader.tsx
  src/pages/Error404.tsx
  src/pages/FindPW.tsx
  src/pages/KakaoSignUp.tsx
  src/pages/LogIn.tsx
Labels: 🐞BugFix

#80 !HOTFIX: Fixed typescript error
  src/components/Home/HomeBody.tsx
  src/components/Intro/Header.tsx
  src/components/KakaoSignUp/KakaoSignUpHeader.tsx
  src/components/LogIn/LogInHeader.tsx
  src/components/SignUp/SignUpHeader.tsx
  src/components/WriteLetter/WriteLetterBody.tsx
  src/components/WriteLetter/WriteLetterTermModalComponent.tsx
  src/pages/SignUp.tsx
  src/pages/WriteLetter.tsx
  src/utils/interceptors/onRequest.ts
  tsconfig.json
Labels: 🐞BugFix

#81 Feat: Implement about letter page
  .env
  index.html
  package-lock.json
  package.json
  src/App.tsx
  src/AppRouter.tsx
  src/apis/life/letter/createMyLetter.ts
  src/apis/life/letter/getMyLetter.ts
  src/apis/life/letter/getOtherLetterList.ts
  src/apis/life/memory/getMyMemoryCard.ts
  src/apis/life/templetter/createTempLetter.ts
  src/apis/users/signIn.ts
  src/apis/users/signup.ts
  src/components/AfterWrite/AnswerGPT.tsx
  src/components/AfterWrite/Loading.tsx
  src/components/AfterWrite/SpeechBubbleContent.tsx
  src/components/AfterWrite/TheMoon.tsx
  src/components/AfterWrite/YourHelp.tsx
  src/components/Common/CommonContentContainer.tsx
  src/components/Common/FullModal.tsx
  src/components/Common/PageContainer.tsx
  src/components/Common/ResizableBottomSheet.tsx
  src/components/Home/HomeBody.tsx
  src/components/KakaoSignUp/KakaoSignUpBody.tsx
  src/components/LogIn/LogInBody.tsx
  src/components/SignUp/SignUpAgreeModalContent.tsx
  src/components/ViewMyLetter/LetterHeader.tsx
  src/components/ViewMyLetter/ViewMyLetterPost.tsx
  src/components/ViewMyLetter/ViewMyMemoryCard.tsx
  src/components/ViewOtherLetter/ViewOtherLetterBody.tsx
  src/components/ViewOtherLetter/ViewOtherLetterFilter.tsx
  src/components/ViewOtherLetter/ViewOtherLetterHeader.tsx
  src/components/ViewOtherLetter/atoms/FilterAtom.ts
  src/components/ViewOtherLetter/atoms/isActiveFilterAtoms.ts
  src/components/WriteLetter/WriteLetterBody.tsx
  src/components/WriteLetter/WriteLetterHeader.tsx
  src/components/WriteLetter/atoms/isValidPostAtom.ts
  src/components/WriteLetter/atoms/myLetterAtoms.ts
  src/index.css
  src/pages/Error404.tsx
  src/pages/Intro.tsx
  src/pages/KakaoSignUp.tsx
  src/pages/LogIn.tsx
  src/pages/MainContentFirst.tsx
  src/pages/ModifyLetter.tsx
  src/pages/OnBording.tsx
  src/pages/ViewMyLetter.tsx
  src/pages/ViewOtherLetter.tsx
  src/state/tokenState.ts
  src/utils/getTimeDifference.ts
  src/utils/interceptors/getRefreshToken.ts
  src/utils/interceptors/onErrorResponse.ts
  src/utils/interceptors/onRequest.ts
  src/utils/interceptors/onResponse.ts
  src/vite-env.d.ts
  vite.config.ts
Labels: ✨ Feature, 📮 API, 🎨 html&css

#82 !HOTFIX: Fix build error
  src/components/AfterWrite/YourHelp.tsx
  src/components/LogIn/LogInBody.tsx
  src/components/ViewMyLetter/LetterHeader.tsx
  src/components/ViewMyLetter/ViewMyLetterPost.tsx
  src/components/WriteLetter/WriteLetterHeader.tsx
  src/pages/Intro.tsx
  src/pages/KakaoSignUp.tsx
  src/pages/ViewMyLetter.tsx
  src/utils/interceptors/onRequest.ts
  src/utils/interceptors/onResponse.ts
Labels: 🐞BugFix

#86 !HOTFIX: hidden scroll bar
  src/AppRouter.tsx
  src/components/ModifyLetter/ModifyLetterBody.tsx
  src/components/ModifyLetter/ModifyLetterHeader.tsx
  src/pages/ModifyLetter.tsx
Labels: 🐞BugFix

#103 Fix: 온보딩 UI 개선
  .env
  src/AppRouter.tsx
  src/components/ChangeUserInfo/ChangeUserInfoBody.tsx
  src/components/Common/CommonContentContainer.tsx
  src/components/Home/HomeBody.tsx
  src/components/ViewMyLetter/LetterHeader.tsx
  src/components/ViewMyLetter/ViewMyLetterPost.tsx
  src/components/WriteCard/WriteCardBody.tsx
  src/components/WriteCard/WriteCardHeader.tsx
  src/pages/MainContentCard.tsx
  src/pages/MainContentSecond.tsx
  src/pages/ViewOtherLetterPost.tsx
  src/pages/WillBeforeQuestion.tsx
  src/pages/WriteCard.tsx
Labels: 🎨 html&css, 🐞BugFix

#131 Feat: Add get user email API
  src/apis/users/getUserEmail.ts
  src/components/ChangeUserInfo/ChangeUserInfoBody.tsx
Labels: 📮 API
