Repository hackathon20230505/weliving_Front, pull requests merged in 2023-05, with the labels that each got.

#2 [#1] Create 🎉 Create React Vite Typescript repo
  .eslintrc.cjs
  .gitignore
  index.html
  package-lock.json
  package.json
  src/App.css
  src/App.tsx
  src/index.css
  src/main.tsx
  src/vite-env.d.ts
  tsconfig.json
  tsconfig.node.json
  vite.config.ts
Labels: enhancement

#4 [#3] Chore ➕ Install styled-components
  package-lock.json
  package.json
Labels: ⚙️ Setting

#5 [#3] Chore ➕ Install React Router DOM
  package-lock.json
  package.json
Labels: ⚙️ Setting

#6 [#3] Feat ✨ Set Router Intro, Home, LogIn pages and header, footer
  src/App.tsx
  src/AppRouter.tsx
  src/components/common/Footer.tsx
  src/components/common/Header.tsx
  src/pages/Home.tsx
  src/pages/Intro.tsx
  src/pages/LogIn.tsx
Labels: ⚙️ Setting

#7 [#3] Design 💄 Create global color variable
  src/index.css
Labels: 🎨 html&css, ⚙️ Setting

#9 [#3] Design 💄 Limit #root width
  src/index.css
Labels: 🎨 html&css, ⚙️ Setting

#10 [#3] Design 💄 Set Font Pretandard
  index.html
  src/index.css
Labels: 🎨 html&css, ⚙️ Setting

#12 [#11] Chore ➕ Set prettier & eslint
  .prettierrc
  package-lock.json
  package.json
Labels: ⚙️ Setting

#15 [#14] Chore 🙈 Add vite pre-building file in .gitignore
  .gitignore
Labels: ⚙️ Setting

#17 [#13] Docs 📝 Add commit convention in README.md
  README.md
Labels: 📜 Docs

#18 [#16] Feat ✨ Set axios baseURL
  package-lock.json
  package.json
  src/App.tsx
Labels: ⚙️ Setting

#21 Feat: Add TalkingToCatIntro.tsx
  src/pages/TalkingToCatIntro.tsx
Labels: 🎨 html&css

#25 [#19] Design 💄 Update global style
  src/index.css
Labels: 🎨 html&css

#33 [#32] Feat: Add NotFound Page in Router
  src/App.tsx
  src/AppRouter.tsx
  src/pages/Error404.tsx
Labels: ✨ Feature, 🎨 html&css

#37 [#36] Remove: Move Header component's place in Intro page
  src/AppRouter.tsx
  src/components/common/Footer.tsx
  src/components/common/Header.tsx
  src/pages/Intro.tsx
Labels: 🔨 Refactor

#38 [#34] Feat: Implement LogIn page
  src/components/LogIn/LogInBody.tsx
  src/components/LogIn/LogInHeader.tsx
  src/index.css
  src/pages/Intro.tsx
  src/pages/LogIn.tsx
Labels: 🎨 html&css

#39 [#36] Refactor: Move Intro Header component
  src/components/Intro/Header.tsx
Labels: 🔨 Refactor
